insert into cozinha (nome) values ('Amazonense');
insert into cozinha (nome) values ('Mineira');
insert into cozinha (nome) values ('Italiana');
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Cantinho do Burguer', 4.76, 2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Vini burguer', 3.80, 2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Paçai', 7.80, 1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Forno da saudade', 1.15, 3);
insert into estado (nome) values ('Minas Gerais');
insert into estado (nome) values ('São Paulo');
insert into estado (nome) values ('Rio Grande do Sul');
insert into estado (nome) values ('Santa Catarina');
insert into cidade (nome, estado_id) values ('Capinas', 2);
insert into cidade (nome, estado_id) values ('Porto Alegre', 3);
insert into cidade (nome, estado_id) values ('Florianopolis', 4);
insert into cidade (nome, estado_id) values ('Belo Horizonte', 1);
